dist: bionic
addons:
  apt:
    packages:
      - fakeroot
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  -
    file: target/debian/bintray.json
    key:
      secure: "QQw43FXVZMgmfoQUXL/e3/oJpLkofvmgPYEXpki0JG9Z6w1sSFl65R8DzLXwtjqgE5X8qV2IhXzplMwtS/YcEU50Dkb5Vj5+Wtj09OPNM8huAPiC6XN4Oz3TknIAsMHNU+WXzVH1+z+o2Dat+htL1EThbZtdP66VN1Mq7oldCCY="
    on:
      tags: true
      repo: lucidsoftware/piezo
    provider: bintray
    skip_cleanup: true
    user: lucidchart
  -
    api_key:
      secure: eykUoy/ImC0ATe30a7QBwTCgRNc4X/EGV0EpxUXY/PFk69O562kcn/fTTbw2HDWbJoUFWFV75HP/RxTOqdvp5aywghGY8YGFfhS5k1px9vg/ypLGyJYse7SHc1t24EzP6T/wlrRgb7viGkgo6vxH91MThBolLCz0GPu5UN55Tqo=
    file:
      - admin/target/*.deb
      - worker/target/**/*.jar
    file_glob: true
    on:
      tags: true
      repo: lucidsoftware/piezo
    provider: releases
    skip_cleanup: true
git:
  depth: 1
jdk:
  - openjdk8
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - sbt compile test doc
after_success:
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      if [ -z "$TRAVIS_TAG" ]; then
          sbt publishSigned
      else
          sbt '; publishSigned; sonatypeBundleRelease'
      fi
    fi
before_install:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
