name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Env
        if: ${{ github.repository == 'lucidsoftware/piezo' }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            version="${GITHUB_REF#refs/tags/}"
          else
            version="${GITHUB_REF#refs/branches/}-SNAPSHOT"
          fi
          echo "SBT_OPTS=-Dbuild.version=$version" >> $GITHUB_ENV
      - name: Test
        run: sbt compile test doc
      - name: Publish to Sonatype
        if: ${{ github.repository == 'lucidsoftware/piezo' }}
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          echo "$PGP_SECRET" | base64 --decode | gpg --import
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            sbt '; publishSigned; sonatypeBundleRelease'
          else
            sbt publishSigned
          fi
      - name: Upload assets to Github
        if: ${{ github.action_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag="${GITHUB_REF#refs/tags/}"
          args=$(printf -- "-a %q " {admin,worker}/target/**/*.jar)
          hub release create $args -m "Release $tag" $tag
